[package]
authors = ["Luis Osta <luisosta1999@gmail.com>"]
edition = "2018"
name = "rust-db-generation"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.0.0"
mongodb = "2.0.0"
tokio = "1.4.0"
